## Logistic Regression

In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression

In [8]:
df = pd.read_csv('spam_detection_dataset.csv')
df.head()

   num_links  num_words  has_offer  sender_score  all_caps  is_spam
0          3         98          1      0.718607         0        0
1          0        170          0      0.698901         1        0
2          0         38          0      0.620466         0        0
3          0        116          0      0.701755         0        0
4          3         89          1      0.583621         1        1

In [9]:
df = pd.read_csv('spam_detection_dataset.csv')
df.head()

   num_links  num_words  has_offer  sender_score  all_caps  is_spam
0          3         98          1      0.718607         0        0
1          0        170          0      0.698901         1        0
2          0         38          0      0.620466         0        0
3          0        116          0      0.701755         0        0
4          3         89          1      0.583621         1        1

In [11]:
print(df.info())
print("\nMissing values:\n", df.isnull().sum())
print("\nStatistical Summary:\n", df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   num_links     20000 non-null  int64
 1   num_words     20000 non-null  int64
 2   has_offer     20000 non-null  int64
 3   sender_score  20000 non-null  float64
 4   all_caps      20000 non-null  int64
 5   is_spam       20000 non-null  int64
dtypes: float64(1), int64(5)
memory usage: 937.6 KB
None

Missing values:
 num_links       0
num_words       0
has_offer       0
sender_score    0
all_caps        0
is_spam         0
dtype: int64

Statistical Summary:
           num_links     num_words     has_offer  sender_score      all_caps  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.000000
mean       1.497300    109.506150      0.302750      0.694248      0.097800
std        1.220478     51.969579      0.459459      0.188312      0.297051
min        0.000000     20.000000      0.000000      0.000000      0.000000
25%        1.000000     64.000000      0.000000      0.567073      0.000000
50%        1.000000    110.000000      0.000000      0.699740      0.000000
75%        2.000000    154.000000      1.000000      0.834083      0.000000
max        9.000000    199.000000      1.000000      1.000000      1.000000

           is_spam
count  20000.00000
mean       0.09175
std        0.28868
min        0.00000
25%        0.00000
50%        0.00000
75%        0.00000
max        1.00000

In [ ]:
#selecting the feature and target columns
y= df['is_spam'].values
X=X= df.drop("is_spam", axis=1)

array([0, 0, 0, ..., 0, 0, 0], shape=(20000,))

In [15]:
#Splitting the data into train and test
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
import numpy as np

class logisticregression:
    def __init__(self, lr=0.01, epochs=1000, reg_lamda=0.1):
        self.lr = lr
        self.epochs = epochs
        self.reg_lamda = reg_lamda

    def sigmoid(self, z):
        z = np.clip(z, -500, 500)
        return 1 / (1 + np.exp(-z))

    def compute_loss(self, h, y):
        m = y.shape[0]
        # To avoid log(0)
        epsilon = 1e-15
        h = np.clip(h, epsilon, 1 - epsilon)
        loss = -1/m * (np.dot(y, np.log(h)) + np.dot(1 - y, np.log(1 - h)))
        reg_term = self.reg_lamda / (2 * m) * np.sum(self.theta[1:] ** 2)
        return loss + reg_term

    def fit(self, X, y):
        m, n = X.shape
        self.theta = np.zeros(n)

        for epoch in range(self.epochs):
            predictions = self.sigmoid(np.dot(X, self.theta))
            errors = predictions - y

            gradient = np.dot(X.T, errors) / m
            gradient[1:] += (self.reg_lamda / m) * self.theta[1:]

            self.theta -= self.lr * gradient
            if epoch % 100 == 0 or epoch == 1:  # Print every 100 epochs and at 1st epoch
                loss = self.compute_loss(predictions, y)
                print(f"Epoch {epoch}/{self.epochs} - Loss: {loss:.4f}")

    def predict(self, X):
        z = np.dot(X, self.theta)
        return self.sigmoid(z) >= 0.5

In [34]:
#Training the model
model = logisticregression(lr=0.1, epochs=2000, reg_lamda=0.1)
model.fit(X_train, y_train)
# y_pred=model.predict(X_val)

Epoch 0/2000 - Loss: 0.6932
Epoch 1/2000 - Loss: 3.1647
Epoch 100/2000 - Loss: 3.1646
Epoch 200/2000 - Loss: 29.8630
Epoch 300/2000 - Loss: 3.1648
Epoch 400/2000 - Loss: 3.1648
Epoch 500/2000 - Loss: 3.1648
Epoch 600/2000 - Loss: 3.1647
Epoch 700/2000 - Loss: 3.1647
Epoch 800/2000 - Loss: 3.1647
Epoch 900/2000 - Loss: 3.1629
Epoch 1000/2000 - Loss: 3.1296
Epoch 1100/2000 - Loss: 2.9862
Epoch 1200/2000 - Loss: 2.6796
Epoch 1300/2000 - Loss: 2.9434
Epoch 1400/2000 - Loss: 3.1626
Epoch 1500/2000 - Loss: 10.6885
Epoch 1600/2000 - Loss: 4.2076
Epoch 1700/2000 - Loss: 3.1078
Epoch 1800/2000 - Loss: 3.1633
Epoch 1900/2000 - Loss: 3.1167

In [36]:
y_pred = model.predict(X_val)

In [38]:
# 3. Evaluation Metrics
# -----------------------------
print("Evaluation (Logistic Regression from Scratch):")
print("Accuracy:", accuracy_score(y_val, y_pred))
print("Precision:", precision_score(y_val, y_pred))
print("Recall:", recall_score(y_val, y_pred))
print("F1 Score:", f1_score(y_val, y_pred))
print()

Evaluation (Logistic Regression from Scratch):
Accuracy: 0.90725
Precision: 0.3333333333333333
Recall: 0.005420054200542005
F1 Score: 0.010666666666666666

In [40]:
#Logistic Refression Using Sklearn
sk = LogisticRegression()
sk.fit(X_train, y_train)
y_pred_sklearn = sk.predict(X_val)

c:\Users\Nhujaw\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [41]:
print("Classification Report (sklearn):")
print(classification_report(y_val, y_pred_sklearn))

Classification Report (sklearn):
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      3631
           1       0.80      0.51      0.62       369

    accuracy                           0.94      4000
   macro avg       0.87      0.75      0.80      4000
weighted avg       0.94      0.94      0.94      4000

### Why accuracy is not always a suitable metric:
    In many real-world problems like spam detection, the classes are often imbalanced — for example, 90% of emails might be non-spam and only 10% spam.

    If a model naively predicts every email as non-spam, it will be correct 90% of the time, resulting in high accuracy.

    However, such a model completely fails to detect any spam emails, which is usually the most important task.

\.

### When to choose precision or recall
    Precision measures how many of the emails flagged as spam are actually spam.
    Choose precision when false positives are costly—for example, if marking a genuine email as spam causes important messages to be missed or creates user frustration.
    In such cases, you want to minimize the number of good emails incorrectly classified as spam.

    Recall measures how many of the actual spam emails are correctly detected.
    Choose recall when false negatives are costly—for example, if missing a spam email leads to security risks or annoyance.
    In this case, it’s more important to catch as many spam emails as possible, even if some good emails get mistakenly flagged.

# Explanation of Different Evaluation Metrics

---

### 1. Precision

**Definition:**  
The proportion of positive predictions that are actually correct.

**Formula:**  
$$
\text{Precision} = \frac{TP}{TP + FP}
$$

**Explanation:**  
Out of all emails labeled as spam by the model, how many really are spam?

**When important:**  
When false positives (wrongly labeling legitimate emails as spam) are costly.

---

### 2. Recall (Sensitivity or True Positive Rate)

**Definition:**  
The proportion of actual positives that were correctly identified.

**Formula:**  
$$
\text{Recall} = \frac{TP}{TP + FN}
$$

**Explanation:**  
Out of all real spam emails, how many did the model successfully detect?

**When important:**  
When missing spam emails (false negatives) is costly.

---

### 3. F1 Score

**Definition:**  
The harmonic mean of precision and recall, balancing the two.

**Formula:**  
$$
F1 = 2 \times \frac{\text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}}
$$

**Explanation:**  
Combines precision and recall into a single metric, useful when you want to balance false positives and false negatives.

---

### 4. Accuracy

**Definition:**  
The overall proportion of correct predictions.

**Formula:**  
$$
\text{Accuracy} = \frac{TP + TN}{TP + TN + FP + FN}
$$

**Explanation:**  
Measures how often the model is correct overall.

**Limitation:**  
Can be misleading with imbalanced datasets.

---

### 5. Confusion Matrix

A table showing counts of:

|                      | **Predicted Spam**     | **Predicted Not Spam**  |
|----------------------|------------------------|--------------------------|
| **Actual Spam**       | True Positives (TP)     | False Negatives (FN)     |
| **Actual Not Spam**   | False Positives (FP)    | True Negatives (TN)      |

- **TP:** Correctly predicted spam emails  
- **TN:** Correctly predicted non-spam emails  
- **FP:** Non-spam emails incorrectly labeled as spam  
- **FN:** Spam emails incorrectly labeled as non-spam