## **Pandas Tutoiral Task**

In [5]:
import pandas as pd
#loading the Data Frame
data = {
'Product': ['Laptop', 'Shirt', 'Smartphone', 'Shoes', 'Headphones', 'Watch'],
'Price': [999.99, 29.99, 599.99, 89.99, 199.99, 49.99],
'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']
}
df= pd.DataFrame (data)
df

      Product   Price     Category
0      Laptop  999.99  Electronics
1       Shirt   29.99      Fashion
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics
5       Watch   49.99      Fashion

In [ ]:
#TASK 1
#1. Filter the DataFrame to only include rows where the Price is greater than $50

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

In [13]:
#2. Filter the resulting DataFrame to only include rows where the Category is either "Electronics" or "Fashion"
filter_df = df['Category'].isin(['Electronics ', 'Fashion']) 
filter_df
selected_data = df.loc[filter_df, ['Product', 'Price', 'Category']]
selected_data

  Product  Price Category
1   Shirt  29.99  Fashion
3   Shoes  89.99  Fashion
5   Watch  49.99  Fashion

In [17]:
#TASK 2
data1 = { 'CustomerID': [1, 2, 3, 4], 'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'], 'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St'] }
df1 = pd.DataFrame(data1)
data2=data2 = { 'CustomerID': [1, 2, 1, 3],
'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'],
'TotalAmount': [100.50, 200.75, 150.25, 300.00]
}
df2=pd.DataFrame(data2)
merged_df = pd.merge(df1, df2, on='CustomerID', how='left')
print(merged_df)

   CustomerID           Name       Address   OrderDate  TotalAmount
0           1       John Doe    123 Elm St  2024-01-01       100.50
1           1       John Doe    123 Elm St  2024-01-10       150.25
2           2     Jane Smith    456 Oak St  2024-01-05       200.75
3           3  Alice Johnson   789 Pine St  2024-01-15       300.00
4           4      Bob Brown  101 Maple St         NaN          NaN

In [18]:
#TASK 3
#Create a sample DataFrame
data = {
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
'Sales': [150, 200, 250, 300, 350, 400, 450, 500],
'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']
}
df= pd.DataFrame(data)

In [ ]:
#2 Calculate the total Sales for each region
df1= df.groupby('Region').agg(total = ('Sales', sum))

C:\Users\Nhujaw\AppData\Local\Temp\ipykernel_12120\1826909522.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df1= df.groupby('Region').agg(total = ('Sales', sum))

In [22]:
df1

        total
Region
East      700
North     500
South     600
West      800

In [27]:
#3. Calculate the average Sales for each region
df1= df.groupby('Region').agg(total_avg = ('Sales', 'mean'))
df1

        total_avg
Region
East        350.0
North       250.0
South       300.0
West        400.0