## **Topic 2**

In [72]:
import matplotlib.pyplot as plt

### Intro to AI and Data Science

- **AI**
    - Technology to simulate human intelligence
    1. Acting Humanly
    2. Thinking Humanly
    3. Acting Rationally
    4. Thinking Rationally

- **Data Science**
    - Extract meaningful insights from data for decision making 
    1. Big Data - Enormous Complex Data
    2. Data driven decision making
        - Reduce Risks
        - Cost Savings

- **Application**: *AI for Human Resource Management*
    1. Talent Acquisition (TA)
    2. Learning and Training Programs
    3. Internal Employee Management
    4. Onboarding of new recruits

### Data Wrangling

`Data Munging`, `Data Remediation`
- Clean, transform and prepare raw data into format suited for analysis
- To ensure reliability and completeness of dataset
- Enhance accuracy and value of insights from data

**Six Steps of Data Wrangling**
| **Step**       | **Description**                                                                 |
|----------------|----------------------------------------------------------------------------------|
| **1. Discovery**   | Identify data sources, assess data quality, and understand data format/structure.     |
| **2. Structuring** | Reshape, convert, and fill missing data to ensure a standardized data presentation.  |
| **3. Cleaning**    | Handle inaccuracies, remove duplicates, and fix anomalies for error-free data.        |
| **4. Enriching**   | Merge with external sources and augment data for deeper comprehension.               |
| **5. Validation**  | Ensure data meets quality and integrity standards required for analysis.             |
| **6. Publishing**  | Document the entire process and prepare data for storage or integration.             |

**Titanic Dataset Use Case**

In [73]:
import pandas as pd
import requests
from pathlib import Path

datapath = Path('Data')
datapath.mkdir(parents=True, exist_ok=True)
filepath = datapath / 'titanic_train.csv'

response = requests.get("https://raw.githubusercontent.com/prof-sushil/Data-Science-World/refs/heads/main/data/titanic_train.csv")
with open(filepath, "wb") as f:
    f.write(response.content)

print(f"File saved to {filepath}")

File saved to Data\titanic_train.csv

In [74]:
# Working with the dataset
df = pd.read_csv("Data/titanic_train.csv")
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [75]:
df.shape # Rows (Datapoints), Columns

(891, 12)

In [76]:
df.describe() # Statistical Description

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [77]:
df.info() # Summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [78]:
# Inspecting the data
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [79]:
df.duplicated().sum() # No duplicates

np.int64(0)

In [80]:
# Checking an important column
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

**Handling Missing Values**
- Impute (Predictive Models, Group Stats, Mean , Median, Mode)
- Drop missing (If number is large)

In [81]:
df["Cabin"].isnull().sum() # Large number of missing

np.int64(687)

In [82]:
df["Age"].isnull().sum() # Fairly low

np.int64(177)

In [83]:
df["Embarked"].isnull().sum() # Negligible

np.int64(2)

In [84]:
# Drop Cabin
df = df.drop("Cabin", axis=1)

# Mean Imputation for Age
mean_age = df["Age"].mean()
df["Age"] = df["Age"].fillna(mean_age)

# Mode Imputation for Embarked
mode_embarked = df["Embarked"].mode()[0]
df["Embarked"] = df["Embarked"].fillna(mode_embarked)

# Checking after handling all missing values
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

**Feature types:**

1. Categorical
    - Nominal: Unordered, no quantitative values\
        - Example: (RGB), (Male, Female)
    - Ordinal: Ordered, Ranked
        - Example: (Poor, Fair, Good), (Unsatisfied, Neutral, Satisfied)

2. Numeric
    - Discrete: Integer 
    - Continuous: Float

**Encoding Categorical Values**

- Convert to Numerical Format  
  - **Label Encoding**: Ordinal  
    - Assign unique integer to each category  
      - Example: (Bad, Neutral, Good) ➡️ (0, 1, 2)  

  - **One Hot Encoding**: Nominal  
    - Column representation of presence and absence  
      - Example: [Red, Yellow, Green] ➡️ [1, 0, 0]  

    - OHE Drawback  
      - Increased dimensionality  
      - Computational inefficiency  

    - Solution is **Frequency Encoding**

In [85]:
columns = df.columns
columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [86]:
categorical = df.dtypes[df.dtypes == "object"].index
categorical

Index(['Name', 'Sex', 'Ticket', 'Embarked'], dtype='object')

In [87]:
numerical = df.dtypes[df.dtypes == "int"].index
numerical

Index(['PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch'], dtype='object')

In [88]:
# Unique Categorical
for cat in categorical:
    print(f"Number of unique values in {cat}: {len(df[cat].unique())}")

Number of unique values in Name: 891
Number of unique values in Sex: 2
Number of unique values in Ticket: 681
Number of unique values in Embarked: 3

In [89]:
"""
Using One Hot Encoding on Name, Ticket isn't efficient 
But we can apply OHE on Sex, Embarked
"""
df_SeEmb = df[["Sex", "Embarked"]]
df_SeEmb

        Sex Embarked
0      male        S
1    female        C
2    female        S
3    female        S
4      male        S
..      ...      ...
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

[891 rows x 2 columns]

In [ ]:
df_SeEmb_encoded = pd.get_dummies(df_SeEmb) # Add. Args `columns`, `drop_first`
df_SeEmb_encoded

"""
`drop_first`: Keeps all info, uses fewer columns
"""

     Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0         False      True       False       False        True
1          True     False        True       False       False
2          True     False       False       False        True
3          True     False       False       False        True
4         False      True       False       False        True
..          ...       ...         ...         ...         ...
886       False      True       False       False        True
887        True     False       False       False        True
888        True     False       False       False        True
889       False      True        True       False       False
890       False      True       False        True       False

[891 rows x 5 columns]

In [92]:
df_SeEmb_encoded.shape

(891, 5)

In [95]:
# Using SkLearn for Label Encoding
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df_copy = df.copy()

df_copy["Embarked"] = label_encoder.fit_transform(df_copy["Embarked"])

df_copy.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.00,2
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.00,2
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.45,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.00,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.75,1

In [96]:
# Saving the cleaned dataset
df_SeEmb_encoded.to_csv("Data/cleaned_SeEmb.csv", index=False)