In [7]:
!pip3 install wget — quiet
!pip3 install openai==1.3.3 — quiet
!pip3 install sentence-transformers — quiet

ERROR: Invalid requirement: '—'
ERROR: Invalid requirement: '—'
ERROR: Invalid requirement: '—'

In [8]:
!pip3 install wget
!pip3 install openai==1.3.3
!pip3 install sentence-transformers

Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=cdb1bce88859d064eebf5c9ceaa7ec7aee0ff81d9ce92dfaeadfcfb5371eabc4
  Stored in directory: /home/jovyan/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2
Collecting openai==1.3.3
  Downloading openai-1.3.3-py3-none-any.whl.metadata (16 kB)
Collecting anyio<4,>=3.5.0 (from openai==1.3.3)
  Downloading anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/conda/lib/python3.11/site-packages (from openai==1.3.3) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/conda/lib/python3.11/site-packages (from openai==1.3.3) (0.27.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/conda/lib/python3.11/site-packages (from openai==1.3.3) (2.11.5)
Requirement already satisfied: tqdm>4 in /opt/conda/lib/python3.11/site-packages (from openai==1.3.3) (4.66.4)
Requirement already satisfied: typing-extensions<5,>=4.5 in /opt/conda/lib/python3.11/site-packages (from openai==1.3.3) (4.13.2)
Requirement already satisfied: idna>=2.8 in /opt/conda/lib/python3.11/site-packages (from anyio<4,>=3.5.0->openai==1.3.3) (3.3)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.11/site-packages (from anyio<4,>=3.5.0->openai==1.3.3) (1.3.1)
Requirement already satisfied: certifi in /opt/conda/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai==1.3.3) (2024.7.4)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai==1.3.3) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/conda/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai==1.3.3) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==1.3.3) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/conda/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==1.3.3) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/conda/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==1.3.3) (0.4.1)
Downloading openai-1.3.3-py3-none-any.whl (220 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.3/220.3 kB 49.1 MB/s eta 0:00:00
Downloading anyio-3.7.1-py3-none-any.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.9/80.9 kB 43.7 MB/s eta 0:00:00
Installing collected packages: anyio, openai
  Attempting uninstall: anyio
    Found existing installation: anyio 4.3.0
    Uninstalling anyio-4.3.0:
      Successfully uninstalled anyio-4.3.0
  Attempting uninstall: openai
    Found existing installation: openai 1.82.1
    Uninstalling openai-1.82.1:
      Successfully uninstalled openai-1.82.1
Successfully installed anyio-3.7.1 openai-1.3.3
Collecting sentence-transformers
  Downloading sentence_transformers-4.1.0-py3-none-any.whl.metadata (13 kB)
Collecting transformers<5.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-4.52.4-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from sentence-transformers) (4.66.4)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.7.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting scikit-learn (from sentence-transformers)
  Downloading scikit_learn-1.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (17 kB)
Collecting scipy (from sentence-transformers)
  Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 36.2 MB/s eta 0:00:00
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/conda/lib/python3.11/site-packages (from sentence-transformers) (0.32.3)
Collecting Pillow (from sentence-transformers)
  Downloading pillow-11.2.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/conda/lib/python3.11/site-packages (from sentence-transformers) (4.13.2)
Requirement already satisfied: filelock in /opt/conda/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.5.1)
Requirement already satisfied: packaging>=20.9 in /opt/conda/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.31.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /opt/conda/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.2)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch>=1.11.0->sentence-transformers)
  Downloading networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.6.77 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.5.1.17 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.6.4.1 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.3.0.4 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.7.77 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.7.1.2 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.4.2 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.3 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.26.2 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvtx-cu12==12.6.77 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nvjitlink-cu12==12.6.85 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufile-cu12==1.11.1.6 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.3.1 (from torch>=1.11.0->sentence-transformers)
  Downloading triton-3.3.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: setuptools>=40.8.0 in /opt/conda/lib/python3.11/site-packages (from triton==3.3.1->torch>=1.11.0->sentence-transformers) (70.0.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.11/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.11/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /opt/conda/lib/python3.11/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.1)
Collecting safetensors>=0.4.3 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting joblib>=1.2.0 (from scikit-learn->sentence-transformers)
  Downloading joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn->sentence-transformers)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.7.4)
Downloading sentence_transformers-4.1.0-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.7/345.7 kB 108.3 MB/s eta 0:00:00
Downloading torch-2.7.1-cp311-cp311-manylinux_2_28_x86_64.whl (821.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 821.2/821.2 MB 20.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 31.4 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 52.3 MB/s eta 0:00:00a 0:00:01
Downloading nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 78.7 MB/s eta 0:00:0000:0100:01m
Downloading nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 97.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl (571.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 19.8 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 53.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cufile_cu12-1.11.1.6-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 55.0 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 69.3 MB/s eta 0:00:00:00:010:01m
Downloading nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 77.9 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 63.5 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl (156.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.8/156.8 MB 47.0 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nccl_cu12-2.26.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (201.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 MB 67.4 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 68.8 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 25.1 MB/s eta 0:00:00
Downloading triton-3.3.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (155.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.7/155.7 MB 79.8 MB/s eta 0:00:0000:0100:01
Downloading transformers-4.52.4-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 156.4 MB/s eta 0:00:00 0:00:01
Downloading pillow-11.2.1-cp311-cp311-manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 172.0 MB/s eta 0:00:00
Downloading scikit_learn-1.7.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 188.7 MB/s eta 0:00:00 0:00:01
Downloading scipy-1.15.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.7/37.7 MB 124.9 MB/s eta 0:00:0000:0100:01
Downloading joblib-1.5.1-py3-none-any.whl (307 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 41.2 MB/s eta 0:00:00
Downloading safetensors-0.5.3-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 97.2 MB/s eta 0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 100.2 MB/s eta 0:00:00 0:00:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading networkx-3.5-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 78.7 MB/s eta 0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 52.2 MB/s eta 0:00:00
Installing collected packages: nvidia-cusparselt-cu12, mpmath, triton, threadpoolctl, sympy, scipy, safetensors, Pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, joblib, scikit-learn, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, transformers, torch, sentence-transformers
Successfully installed Pillow-11.2.1 joblib-1.5.1 mpmath-1.3.0 networkx-3.5 nvidia-cublas-cu12-12.6.4.1 nvidia-cuda-cupti-cu12-12.6.80 nvidia-cuda-nvrtc-cu12-12.6.77 nvidia-cuda-runtime-cu12-12.6.77 nvidia-cudnn-cu12-9.5.1.17 nvidia-cufft-cu12-11.3.0.4 nvidia-cufile-cu12-1.11.1.6 nvidia-curand-cu12-10.3.7.77 nvidia-cusolver-cu12-11.7.1.2 nvidia-cusparse-cu12-12.5.4.2 nvidia-cusparselt-cu12-0.6.3 nvidia-nccl-cu12-2.26.2 nvidia-nvjitlink-cu12-12.6.85 nvidia-nvtx-cu12-12.6.77 safetensors-0.5.3 scikit-learn-1.7.0 scipy-1.15.3 sentence-transformers-4.1.0 sympy-1.14.0 threadpoolctl-3.6.0 torch-2.7.1 transformers-4.52.4 triton-3.3.1

In [11]:
import json
import os
import pandas as pd
import wget

In [19]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('flax-sentence-embeddings/all_datasets_v3_mpnet-base')

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/383 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [15]:
cvs_file_path = 'https://raw.githubusercontent.com/openai/openai-cookbook/main/examples/data/AG_news_samples.csv'
file_path = 'AG_news_samples.csv'

if not os.path.exists(file_path):
    wget.download(cvs_file_path, file_path)
    print('File downloaded successfully.')
else:
    print('File already exists in the local file system.')

df = pd.read_csv('AG_news_samples.csv')
df

File downloaded successfully.

,title,description,label_int,label
0,World Briefings,BRITAIN: BLAIR WARNS OF CLIMATE THREAT Prime M...,1,World
1,Nvidia Puts a Firewall on a Motherboard (PC Wo...,PC World - Upcoming chip set will include buil...,4,Sci/Tech
2,"Olympic joy in Greek, Chinese press",Newspapers in Greece reflect a mixture of exhi...,2,Sports
3,U2 Can iPod with Pictures,"SAN JOSE, Calif. -- Apple Computer (Quote, Cha...",4,Sci/Tech
4,The Dream Factory,"Any product, any shape, any size -- manufactur...",4,Sci/Tech
...,...,...,...,...
1995,You Control: iTunes puts control in OS X menu ...,MacCentral - You Software Inc. announced on Tu...,4,Sci/Tech
1996,Argentina beat Italy for place in football final,Favourites Argentina beat Italy 3-0 this morni...,2,Sports
1997,NCAA case no worry for Spurrier,Shortly after Steve Spurrier arrived at Florid...,2,Sports
1998,Secret Service Busts Cyber Gangs,The US Secret Service Thursday announced arres...,4,Sci/Tech
1999,Stocks Flat; Higher Oil Limits Gains,US stocks were little changed on Thursday as a...,3,Business

In [16]:
data = df.to_dict(orient='records')
data[0]

{'title': 'World Briefings',
 'description': 'BRITAIN: BLAIR WARNS OF CLIMATE THREAT Prime Minister Tony Blair urged the international community to consider global warming a dire threat and agree on a plan of action to curb the  quot;alarming quot; growth of greenhouse gases.',
 'label_int': 1,
 'label': 'World'}

In [17]:
%%sql

DROP TABLE IF EXISTS news_articles;
CREATE TABLE IF NOT EXISTS news_articles (
    title TEXT,
    description TEXT,
    genre TEXT,
    embedding BLOB,
    FULLTEXT(title, description)
);

++
||
++
++

In [20]:
descriptions = [row['description'] for row in data]
all_embeddings = model.encode(descriptions)
all_embeddings.shape

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

(2000, 768)

In [22]:
for row, embedding in zip(data, all_embeddings):
    row['embedding'] = embedding

In [23]:
data[0]

{'title': 'World Briefings',
 'description': 'BRITAIN: BLAIR WARNS OF CLIMATE THREAT Prime Minister Tony Blair urged the international community to consider global warming a dire threat and agree on a plan of action to curb the  quot;alarming quot; growth of greenhouse gases.',
 'label_int': 1,
 'label': 'World',
 'embedding': array([-1.42552713e-02, -1.03357071e-02,  1.25946105e-02,  8.40715785e-03,
        -6.92264410e-03, -8.77237227e-03, -5.38323671e-02,  1.95311196e-02,
         9.50564742e-02,  1.60899572e-02,  4.72200625e-02,  2.30231155e-02,
        -6.69442937e-02,  2.82599987e-03,  2.79738400e-02, -6.46088347e-02,
         5.52451760e-02, -4.02353071e-02, -2.22880822e-02, -1.65119395e-02,
         3.61824557e-02,  3.32110142e-03,  1.18329516e-02,  7.70277716e-03,
        -4.18954827e-02, -2.76368838e-02,  3.64982933e-02,  3.69321145e-02,
         5.97776957e-02,  8.05662386e-03,  3.38091105e-02, -1.52911590e-02,
         1.38111366e-02, -4.00905032e-03,  3.15332080e-08,  2.20769504e-03,
         3.78836691e-03, -1.83615256e-02,  1.49200745e-02, -1.62021983e-02,
        -5.16570453e-03, -8.89025070e-03,  6.39182806e-04,  2.90938653e-02,
        -6.70327619e-02,  8.33853893e-03, -7.37016380e-04,  3.79642798e-03,
         2.53367070e-02,  4.11500176e-03, -7.02746958e-03,  8.54118988e-02,
         1.05591035e-02, -8.18551611e-03, -8.49048868e-02, -2.57210108e-03,
         3.90590318e-02, -6.48996532e-02, -3.32521796e-02,  2.81049777e-02,
        -6.10832423e-02,  6.69943467e-02, -4.27179411e-02,  1.76054183e-02,
        -2.59039514e-02,  3.61620728e-03, -3.28656584e-02,  3.43255475e-02,
        -1.87855288e-02, -2.37692427e-03,  6.34802133e-02,  3.52227525e-03,
        -8.37399624e-03, -3.69816683e-02, -4.92576836e-03, -1.43912463e-02,
         4.51099314e-03, -3.04060727e-02, -2.63304245e-02,  3.67081870e-04,
         1.70523692e-02,  2.23825127e-02, -3.09174675e-02,  7.10717812e-02,
        -3.01759206e-02,  3.54348756e-02, -1.56738255e-02, -1.83105338e-02,
        -1.92053076e-02, -1.22046535e-04,  6.22055084e-02,  2.54733507e-02,
        -3.10839117e-02, -5.74624278e-02, -2.32461877e-02,  4.22174707e-02,
        -9.41116549e-03,  6.37731850e-02,  2.42851605e-03, -4.85859737e-02,
        -1.50168482e-02, -2.94507132e-03,  9.25563183e-03,  2.00727675e-02,
         3.24376076e-02,  3.43225934e-02, -2.43766978e-02, -2.71643605e-02,
        -3.29889432e-02, -8.47245287e-03, -4.84543946e-03,  9.67332441e-03,
        -1.14107532e-02, -4.98367921e-02,  4.26452756e-02,  8.45770352e-03,
         2.94373278e-02,  1.92396734e-02, -5.38313016e-02,  2.42084172e-02,
         3.50646339e-02, -5.94281033e-03,  2.22675465e-02, -1.69157330e-02,
         3.39363404e-02, -4.13312800e-02,  1.79867521e-02, -1.14774927e-02,
         2.99579240e-02, -5.41513450e-02, -5.43640368e-02, -4.82811183e-02,
         3.21459211e-02, -3.83581757e-03,  9.11049265e-03,  4.27778140e-02,
         2.48107873e-02,  1.68477204e-02,  7.58214816e-02, -5.22502093e-03,
        -4.17706184e-02,  4.24156040e-02,  2.13487726e-02,  5.46558835e-02,
         5.30002033e-03, -2.01402400e-02,  4.35316563e-02,  2.31804494e-02,
        -3.35986055e-02, -9.46438406e-03,  1.89928617e-02, -8.60003103e-03,
        -3.65846008e-02, -2.84477919e-02, -5.79532161e-02, -1.20574739e-02,
        -3.37555781e-02,  2.86774766e-02,  4.29633558e-02, -3.95899937e-02,
        -2.85408385e-02,  2.37257704e-02, -2.26753969e-02,  4.00912799e-02,
        -4.28755321e-02,  6.91774637e-02,  3.19429226e-02, -1.54385595e-02,
         8.84625316e-03, -2.46580467e-02,  2.69825067e-02, -1.68179348e-02,
        -1.54679054e-02,  2.39714365e-02,  5.14461892e-03, -1.47299007e-01,
        -3.78248319e-02,  7.72803053e-02, -2.62951739e-02,  6.47971109e-02,
        -4.56399471e-02,  3.94121371e-02, -4.12573665e-03,  1.12248547e-02,
        -7.51652718e-02,  4.73462744e-04, -9.96975577e-04,  3.05251162e-02,
        -1.22393575e-03,  6.07260037e-03,  9.85797960e-03, -4.08381876e-03,
         3.33492607e-02, -2.38110386e-02, -6.91830218e-02, -1.86078046e-02,
        -1.69193000e-02,  2.32260581e-02, -6.35241866e-02, -1.51593806e-02,
         2.74927020e-02,  1.91271063e-02, -5.48586063e-02, -9.01332647e-02,
        -6.42053708e-02,  2.60688700e-02, -7.02210292e-02, -2.63661463e-02,
        -3.76780443e-02, -2.85192318e-02,  1.86377391e-03,  5.56252245e-03,
        -7.10244384e-03,  2.18082741e-02, -5.76293506e-02, -2.70804744e-02,
        -2.32838113e-02, -3.71369459e-02,  1.02239416e-03,  2.75916420e-02,
         5.51652489e-03,  4.38032821e-02, -1.34218195e-02, -4.46370915e-02,
         2.06688158e-02, -5.80557995e-03, -5.34715094e-02,  1.34323509e-02,
         4.74453950e-03, -3.62846367e-02, -2.92693991e-02,  3.27567793e-02,
         3.82207297e-02, -1.07125388e-02, -4.82419096e-02, -1.13990186e-02,
         6.85237162e-03,  2.61822585e-02,  4.10562791e-02, -4.41341996e-02,
         5.59925288e-02,  3.60376202e-02, -2.28435677e-02, -1.64704528e-02,
        -2.70031672e-02, -2.72507537e-02, -6.03096969e-02, -4.87835845e-03,
        -3.36085893e-02, -8.32210947e-03, -1.30310711e-02,  4.20334674e-02,
         5.61953493e-05, -1.26701584e-02, -3.77816451e-03, -4.00594203e-03,
        -8.69947020e-03, -2.86307954e-03,  1.68664325e-02, -7.56073790e-03,
         1.36874681e-02,  2.37455703e-02, -2.81004105e-02,  4.13804278e-02,
         1.60233937e-02, -2.02180576e-02,  4.80800495e-02,  9.01026372e-03,
        -1.39443409e-02,  1.94556341e-02,  3.96373197e-02,  1.02641247e-02,
        -3.27092297e-02, -2.48404057e-03,  3.58592044e-03, -1.50240967e-02,
         8.79754126e-03, -3.34348418e-02, -2.56592724e-02, -4.56163622e-02,
         4.04508086e-03,  3.36054005e-02,  1.21478280e-02,  1.90625098e-02,
        -2.59944946e-02,  9.21307225e-03, -1.65630691e-02, -3.99237797e-02,
        -5.38072642e-03,  2.02475693e-02, -5.62714450e-02,  3.48296692e-03,
        -5.96230617e-03, -3.57603095e-02, -6.32403493e-02, -3.93211991e-02,
         6.80231154e-02, -3.39336246e-02,  7.45192915e-02, -5.90855516e-02,
         2.58422308e-02, -1.05505763e-02, -5.76440357e-02,  2.10725702e-03,
         1.31231695e-02, -3.95736396e-02,  9.55255330e-02, -1.11358017e-02,
         2.19698325e-02,  1.73953865e-02,  1.52507639e-02, -2.72894949e-02,
         4.41171080e-02,  8.29895288e-02,  1.10833375e-02, -2.20045149e-02,
        -4.64904010e-02, -2.87305042e-02, -1.51881678e-02,  1.94376521e-02,
         2.54293699e-02, -6.37337267e-02, -1.98151004e-02, -4.52792905e-02,
         4.12180051e-02, -3.42727639e-02, -5.24882413e-02,  3.37818824e-02,
         3.37932818e-02, -4.56842035e-02, -9.82934888e-03,  1.50437970e-02,
         7.34113827e-02, -1.07236048e-02, -6.14222810e-02, -2.77404115e-02,
         2.32427530e-02, -7.81671777e-02, -5.42622320e-02, -1.48065283e-03,
        -2.99406368e-02, -2.81500574e-02,  4.38036546e-02, -1.45165203e-02,
        -3.50229628e-02,  6.51108995e-02,  2.31997631e-02, -6.57409037e-05,
        -1.16105722e-02, -4.24324721e-03,  2.58602984e-02,  2.71428227e-02,
        -1.06581403e-02,  3.89474183e-02,  3.19787264e-02, -4.56698611e-02,
         2.83477474e-02, -2.70534586e-02, -4.31417068e-03,  9.73935891e-03,
        -2.83586029e-02,  2.11364217e-02, -4.05200645e-02,  1.47182252e-02,
        -1.21200874e-01,  3.72122265e-02,  2.92154998e-02,  2.56311372e-02,
        -7.42644537e-03,  1.09137818e-02, -4.71110595e-03, -1.42274210e-02,
        -2.04357617e-02, -1.12311561e-02, -6.27443641e-02,  4.34111282e-02,
         6.09061588e-03, -2.66529266e-02,  5.59172817e-02,  2.03929320e-02,
        -1.33644473e-02, -1.06937648e-03,  2.28287447e-02, -2.94755679e-03,
        -9.91604105e-02, -1.61342509e-02, -4.37227488e-02, -4.65732664e-02,
         6.40009940e-02,  7.55879357e-02, -3.82939447e-03,  3.34749520e-02,
         7.15638548e-02, -2.17569713e-02,  5.62327728e-03,  1.04705971e-02,
        -4.84404564e-02, -1.38546592e-02,  1.72707662e-02, -1.49816915e-03,
         2.25641411e-02, -5.69920568e-03,  2.77007576e-02, -5.06240018e-02,
         1.13484953e-02, -2.65616886e-02,  1.01801474e-02,  1.63067132e-02,
         2.58632423e-03,  7.19202589e-03,  2.59683114e-02, -1.96814202e-02,
         5.84391365e-03, -2.13498180e-03,  3.63410078e-02,  3.86375450e-02,
        -7.85228517e-03, -2.28550602e-02,  2.74581164e-02,  3.71293537e-02,
        -1.56287793e-02,  4.67386693e-02,  7.29313865e-02, -1.27962073e-02,
         1.78703871e-02, -3.06333918e-02,  9.98662934e-02,  7.33584315e-02,
         1.08686304e-02, -6.97085410e-02,  1.60741527e-02, -2.09304653e-02,
        -2.60450761e-03, -1.94795951e-02,  8.55406560e-03,  1.74604841e-02,
         2.80507654e-02, -3.46868671e-02,  1.87818855e-02,  6.05483130e-02,
         4.44936194e-02, -1.67367030e-02,  2.76925918e-02,  1.53657915e-02,
        -3.78500707e-02,  2.16994397e-02,  4.90333140e-02,  3.16780657e-02,
         5.89496456e-04, -3.60976048e-02,  2.13377047e-02, -3.19440141e-02,
         2.71400604e-02,  9.46721509e-02,  2.97916587e-02, -8.27123295e-04,
         7.11757988e-02, -7.11754858e-02, -3.66365686e-02,  7.63053633e-03,
         7.56757855e-02,  4.72460862e-08, -6.24601729e-02,  3.05226222e-02,
         2.72832457e-02, -1.64924711e-02,  4.66941819e-02,  2.91004311e-03,
         2.82304976e-02,  1.62870344e-02, -4.57580872e-02, -4.70543057e-02,
         3.59020121e-02,  9.65472125e-03, -4.25603753e-03,  5.52374497e-03,
         1.08717885e-02, -3.28236632e-02,  2.18529459e-02,  5.93239954e-03,
        -2.13450585e-02,  8.21452960e-02, -3.28879915e-02, -2.97434293e-02,
        -7.76868220e-03, -1.94320679e-02,  3.98586951e-02, -8.34299775e-04,
        -4.16864362e-03,  7.07365870e-02, -3.44689153e-02,  4.72044852e-03,
         1.94923673e-02,  9.05167963e-03, -6.16047047e-02, -2.08835583e-03,
         3.51504842e-03,  9.08637196e-02,  6.21846654e-02, -5.39529733e-02,
         7.53470277e-03, -2.35426277e-02,  2.18726136e-02, -6.62635341e-02,
        -1.61992926e-02, -6.65634796e-02,  6.93473667e-02, -2.24409346e-02,
        -7.08433753e-03,  1.34691847e-02, -7.99083058e-03,  1.13482559e-02,
        -6.12448491e-02, -8.43891799e-02, -2.76417993e-02, -6.58830046e-04,
        -1.37841422e-03,  4.26088870e-02, -3.52895185e-02, -1.59230661e-02,
         1.75840817e-02,  1.99987553e-02,  5.33235027e-03, -5.25581278e-02,
        -2.44467929e-02, -1.61214941e-03, -4.42117825e-02, -4.62837406e-02,
        -1.09010451e-02, -4.24110936e-03, -5.84472828e-02,  1.46290073e-02,
         4.12465073e-02, -1.39211779e-02, -5.32210693e-02, -1.19127154e-01,
        -2.11934671e-02, -2.53543407e-02,  4.02045920e-02,  6.26871660e-02,
         4.15431894e-02,  1.72636192e-02,  6.64933324e-02,  3.81383598e-02,
        -2.07448378e-02, -1.31714642e-02,  3.72976847e-02, -4.07032445e-02,
        -5.28494529e-02, -1.53534366e-02,  6.45034686e-02, -6.83664484e-03,
        -4.76327538e-02, -2.47513037e-02, -1.00185703e-02, -1.11933818e-09,
        -2.93851108e-03,  6.11553602e-02, -1.14696659e-02,  3.53714364e-04,
        -1.22697102e-02,  5.05964644e-02,  1.99577156e-02,  2.39535384e-02,
        -6.01370335e-02,  5.17973155e-02, -4.62623276e-02, -5.83880022e-03,
         3.70824384e-03, -2.27582902e-02,  2.37534046e-02, -4.29318994e-02,
         9.37928818e-03,  8.62976816e-03,  4.95108180e-02,  2.84247193e-02,
         8.09776559e-02,  2.11244412e-02,  2.18265112e-02, -4.35806140e-02,
         1.55588398e-02,  1.76161863e-02, -5.22840358e-02, -2.47546490e-02,
         3.45748290e-02, -5.96105047e-02,  3.52547802e-02,  2.74184085e-02,
         2.96476539e-02, -1.29562551e-02, -2.48705130e-02,  5.22639230e-02,
        -2.11547446e-02,  5.11787832e-03,  3.56950192e-03, -6.99099824e-02,
         1.27145369e-02, -5.76382410e-03, -5.20491786e-02,  1.25988163e-02,
        -5.40210195e-02,  2.66520903e-02,  4.76649078e-03, -2.89644673e-03,
        -4.28344011e-02, -5.56558371e-02,  7.64432624e-02,  6.92551304e-03,
        -2.19094176e-02,  6.68487772e-02, -8.04819316e-02,  1.04891166e-01,
        -1.05766475e-03, -2.44611991e-04, -7.43969977e-02,  5.75374030e-02,
         7.75330067e-02,  2.05131583e-02, -4.59680753e-03,  4.57410850e-02,
        -2.33295187e-02,  3.35324593e-02, -1.96684431e-03, -1.07343802e-02,
        -3.33804078e-02, -2.50398517e-02, -1.72444917e-02, -3.30309719e-02,
        -3.17952894e-02,  5.08108810e-02, -2.12618690e-02,  2.13306751e-02,
        -8.73737503e-03,  5.22519574e-02,  6.83948696e-02,  7.89125636e-02,
         9.56171006e-03, -1.63969975e-02,  6.88960627e-02, -2.77960487e-02,
        -9.68733244e-03,  7.50258751e-03, -2.65422277e-02,  5.14044128e-02,
         1.91024952e-02, -3.01824473e-02, -7.57714454e-03,  1.33345947e-02,
         1.05314823e-02,  3.92777612e-03,  3.18918638e-02,  8.58741999e-03,
        -2.94463839e-02, -2.90511716e-02, -1.43669907e-03,  3.08890864e-02,
         1.20497877e-02, -2.02856697e-02, -9.44499113e-03,  7.28506269e-03,
         1.07798039e-03,  3.69306505e-02, -1.15025043e-02,  4.67460137e-03,
        -3.38139827e-03, -3.21811102e-02, -3.11846919e-02,  1.70723908e-02,
         4.69329357e-02, -1.63941421e-02, -9.48457140e-03,  4.84579336e-03,
         5.37876645e-03,  1.14750238e-02, -2.42081727e-03, -4.94465604e-03,
         4.34591696e-02,  4.49020825e-02, -4.38062437e-02,  2.95596719e-02,
         2.08722819e-02,  1.95239522e-02, -5.47555275e-03,  7.27585005e-03,
         1.83392782e-02, -4.07732762e-02,  2.13096160e-02,  3.33087854e-02,
         1.15095993e-07, -1.83636211e-02, -3.03078126e-02,  4.73348461e-02,
         6.03527855e-03, -3.62751670e-02,  2.36555841e-02,  4.86233309e-02,
         2.29472853e-02, -6.78386912e-03,  1.91842653e-02, -1.41639784e-02,
        -4.42321748e-02,  2.52328318e-04, -4.36925814e-02, -1.21909892e-02,
        -6.62261248e-02, -1.12664536e-01, -3.98868583e-02, -3.57628502e-02,
         1.93775594e-02,  6.14434527e-03,  4.53422964e-02,  1.00238137e-02,
        -1.76891615e-03,  2.15303581e-02, -5.21780783e-03, -1.03813186e-02,
        -1.11174323e-01,  7.69659951e-02, -1.00749163e-02,  2.49990840e-02,
        -8.84963013e-03,  5.18088005e-02,  4.32132483e-02, -4.99194674e-03,
        -1.54317133e-02, -6.49741814e-02,  3.16957347e-02,  1.69510764e-04,
         3.39284283e-03, -5.63776447e-03,  1.86225642e-02,  2.44001858e-02,
        -4.63952422e-02, -1.21459905e-02, -2.73153167e-02,  3.74784917e-02,
         3.92500386e-02,  4.69721183e-02,  1.92756820e-02, -2.16394570e-03,
        -4.32543748e-04,  3.81461978e-02,  7.10241590e-03,  2.83709448e-02,
        -3.52787897e-02,  1.61017329e-02,  2.22797953e-02, -4.86393413e-03,
         2.18341500e-02, -2.91900169e-02,  3.45296264e-02, -1.52876591e-02,
         6.99071912e-03,  4.03276831e-03, -2.07533296e-02,  1.84423905e-02,
        -1.71574090e-33,  4.07804064e-02, -5.52660273e-03, -4.51080920e-03,
         2.68024076e-02,  1.85708366e-02,  1.49117783e-02,  2.03583408e-02,
         1.23774894e-02, -1.79837234e-02, -5.21711819e-02, -3.05321086e-02],
       dtype=float32)}

In [24]:
%sql TRUNCATE TABLE news_articles;

import sqlalchemy as sa
from singlestoredb import create_engine

# Use create_table from singlestoredb since it uses the notebook connection URL
conn = create_engine().connect()

statement = sa.text('''
    INSERT INTO news_articles (
        title,
        description,
        genre,
        embedding
    )
    VALUES (
        :title,
        :description,
        :label,
        :embedding
    )
''')

conn.execute(statement, data)

In [26]:
search_query = 'India'
search_embedding = model.encode(search_query)

query_statement = sa.text('''
    SELECT
        title,
        description,
        genre,
        DOT_PRODUCT(embedding, :embedding) AS score
    FROM news_articles
    ORDER BY score DESC
    LIMIT 10
''')

# Execute the SQL statement.
results = pd.DataFrame(conn.execute(query_statement, dict(embedding=search_embedding)))
print(results)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

                                               title  \
0           Militants beat man thought to be from US
1         Bomb at India Independence Parade Kills 15
2        Microsoft Unveils Windows XP for India (AP)
3  4 killed, 54 wounded in three separate attacks...
4   Northeast Indian State Votes Amid Tight Security
5  Why The Open-Source Model Can Work In India (T...
6           Microsoft to Hire Hundreds More in India
7  Bhopal victims commemorate 20th anniversary of...
8  Follow-on shy Aussies lead India by 355 runs (...
9                              No channel for series

                                         description     genre     score
0  HENDALA, Sri Lanka -- Day after day, locked in...     World  0.402497
1  NEW DELHI - A bomb exploded during an Independ...     World  0.346617
2  AP - Microsoft Corp. announced Wednesday that ...  Sci/Tech  0.344941
3  Canadian Press - GAUHATI, India (AP) - Residen...     World  0.337517
4   GUWAHATI, India (Reuters) - People braved a s...     World  0.323705
5  TechWeb - An Indian Institute of Technology pr...  Sci/Tech  0.316087
6   HYDERABAD, India (Reuters) - Microsoft Corp. ...  Business  0.274268
7  AFP - A series of torchlight rallies and vigil...     World  0.267720
8  AFP - Hosts India braced themselves for a harr...     World  0.264600
9  INDIA #39;S cricket chiefs began a frenetic se...    Sports  0.260308

In [27]:
hyb_query = 'Articles about India'
hyb_embedding = model.encode(hyb_query)

# Create the SQL statement.
hyb_statement = sa.text('''
    SELECT
        title,
        description,
        genre,
        DOT_PRODUCT(embedding, :embedding) AS semantic_score,
        MATCH(title, description) AGAINST (:query) AS keyword_score,
        (semantic_score + keyword_score) / 2 AS combined_score
    FROM news_articles
    ORDER BY combined_score DESC
    LIMIT 10
''')

# Execute the SQL statement.
hyb_results = pd.DataFrame(conn.execute(hyb_statement, dict(embedding=hyb_embedding, query=hyb_query)))
hyb_results

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

,title,description,genre,semantic_score,keyword_score,combined_score
0,Why The Open-Source Model Can Work In India (T...,TechWeb - An Indian Institute of Technology pr...,Sci/Tech,0.326729,0.0,0.163365
1,Bomb at India Independence Parade Kills 15,NEW DELHI - A bomb exploded during an Independ...,World,0.324176,0.0,0.162088
2,"4 killed, 54 wounded in three separate attacks...","Canadian Press - GAUHATI, India (AP) - Residen...",World,0.316158,0.0,0.158079
3,Indian minister hits out at textbook praising ...,AFP - An Indian minister said a school text-bo...,World,0.282740,0.0,0.141370
4,PM inaugurates Guru Granth Sahib research cent...,Prime Minister Dr Manmohan Singh inaugurated a...,World,0.274033,0.0,0.137016
5,Turkish press jubilant over green light for EU...,"Adorned with Turkish and EU flags, Turkey #39;...",World,0.263389,0.0,0.131695
6,Northeast Indian State Votes Amid Tight Security,"GUWAHATI, India (Reuters) - People braved a s...",World,0.245400,0.0,0.122700
7,Putin favors veto right for India as permanent...,"In an apparent damage control exercise, Russia...",World,0.242365,0.0,0.121183
8,Blair Battles Own Political Party on UK Iraq P...,Description: NPR #39;s Alex Chadwick talks to ...,World,0.238868,0.0,0.119434
9,Search Engine Forums Spotlight,Links to this week's topics from search engine...,Sci/Tech,0.237496,0.0,0.118748