## Movie Recommendation System Based on Collaborative Filtering

In [6]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
user_ratings_df = pd.read_csv("ratings.csv")
user_ratings_df.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [8]:
movie_metadata = pd.read_csv("movies.csv")
movie_metadata.head()
# movie_metadata = movie_metadata[['title', 'genres']]
# movie_metadata.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [9]:
#combine these dataframes on the common column movieID
movie_data = user_ratings_df.merge(movie_metadata, on='movieId')
movie_data.head()

,userId,movieId,rating,timestamp,title,genres
0,1,296,5.0,1147880044,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
1,1,306,3.5,1147868817,Three Colors: Red (Trois couleurs: Rouge) (1994),Drama
2,1,307,5.0,1147868828,Three Colors: Blue (Trois couleurs: Bleu) (1993),Drama
3,1,665,5.0,1147878820,Underground (1995),Comedy|Drama|War
4,1,899,3.5,1147868510,Singin' in the Rain (1952),Comedy|Musical|Romance

In [10]:
#User-Item Matrix
user_item_matrix = user_ratings_df.pivot(index=['userId'], columns=['movieId'], values='rating').fillna(0)
user_item_matrix

/tmp/ipykernel_17638/1263333150.py:2: PerformanceWarning: The following operation may generate 9597558427 cells in the resulting pandas object.
  user_item_matrix = user_ratings_df.pivot(index=['userId'], columns=['movieId'], values='rating').fillna(0)

MemoryError: Unable to allocate 71.5 GiB for an array with shape (162541, 59047) and data type float64