## Imports

In [7]:
!pip install kagglehub[pandas-datasets]

In [9]:
from gensim.models import Word2Vec

## Load dataset

In [10]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "Corona_NLP_test.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "datatattle/covid-19-nlp-text-classification",
  file_path,
)

df.head()

C:\Users\ArunShrestha\AppData\Local\Temp\ipykernel_12776\4158365362.py:6: DeprecationWarning: load_dataset is deprecated and will be removed in a future version.
  df = kagglehub.load_dataset(

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,1,44953,NYC,02-03-2020,TRENDING: New Yorkers encounter empty supermar...,Extremely Negative
1,2,44954,"Seattle, WA",02-03-2020,When I couldn't find hand sanitizer at Fred Me...,Positive
2,3,44955,NaN,02-03-2020,Find out how you can protect yourself and love...,Extremely Positive
3,4,44956,Chicagoland,02-03-2020,#Panic buying hits #NewYork City as anxious sh...,Negative
4,5,44957,"Melbourne, Victoria",03-03-2020,#toiletpaper #dunnypaper #coronavirus #coronav...,Neutral

In [11]:
df = df[['OriginalTweet']]
df.head()

                                       OriginalTweet
0  TRENDING: New Yorkers encounter empty supermar...
1  When I couldn't find hand sanitizer at Fred Me...
2  Find out how you can protect yourself and love...
3  #Panic buying hits #NewYork City as anxious sh...
4  #toiletpaper #dunnypaper #coronavirus #coronav...

In [12]:
# remove urls
import re

def remove_urls(text):
    try:
        if isinstance(text, str):
            return re.sub(r'http\S+|www\.\S+', '', text)
        return text
    except Exception as e:
        print(f"Error while removing URL: {e}")
        return text
    
df['OriginalTweet'] = df['OriginalTweet'].apply(remove_urls)

In [16]:
sentences = [line.split() for line in df['OriginalTweet']]
w2v = Word2Vec(sentences,  window = 5, workers = 4, min_count = 5)

In [17]:
words = list(w2v.wv.vocab)
words

AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead.
See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4