# Text Cleaning

## Importing data

In [13]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "spam.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/sms-spam-collection-dataset",
  file_path,
  pandas_kwargs={"encoding": "ISO-8859-1"}
)

df.head()

C:\Users\ArunShrestha\AppData\Local\Temp\ipykernel_8844\855155969.py:6: DeprecationWarning: load_dataset is deprecated and will be removed in a future version.
  df = kagglehub.load_dataset(

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [14]:
df.rename(columns={'v1': 'Category', 'v2': 'Message'}, inplace=True)
df.head()

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

## Converting to lowercase

In [15]:
import pandas as pd

df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)
df.head()

C:\Users\ArunShrestha\AppData\Local\Temp\ipykernel_8844\1063163285.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"go until jurong point, crazy.. available only ...",NaN,NaN,NaN
1,ham,ok lar... joking wif u oni...,NaN,NaN,NaN
2,spam,free entry in 2 a wkly comp to win fa cup fina...,NaN,NaN,NaN
3,ham,u dun say so early hor... u c already then say...,NaN,NaN,NaN
4,ham,"nah i don't think he goes to usf, he lives aro...",NaN,NaN,NaN

## remove url using regex

In [18]:
import re

url_pattern = re.compile(f'https?://\S+')

def remove_url(text):
    return url_pattern.sub('', text)

df['Message'] = df['Message'].apply(remove_url)
df.head()

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"go until jurong point, crazy.. available only ...",NaN,NaN,NaN
1,ham,ok lar... joking wif u oni...,NaN,NaN,NaN
2,spam,free entry in 2 a wkly comp to win fa cup fina...,NaN,NaN,NaN
3,ham,u dun say so early hor... u c already then say...,NaN,NaN,NaN
4,ham,"nah i don't think he goes to usf, he lives aro...",NaN,NaN,NaN

## Remove no word and non whitespace character

In [20]:
df = df.replace(to_replace=f'[^\w\s]', value='', regex=True)
df.head()

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,go until jurong point crazy available only in ...,NaN,NaN,NaN
1,ham,ok lar joking wif u oni,NaN,NaN,NaN
2,spam,free entry in 2 a wkly comp to win fa cup fina...,NaN,NaN,NaN
3,ham,u dun say so early hor u c already then say,NaN,NaN,NaN
4,ham,nah i dont think he goes to usf he lives aroun...,NaN,NaN,NaN

## Remove digits

In [22]:
df = df.replace(to_replace=r'\d', value='', regex=True)
df.head()

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,go until jurong point crazy available only in ...,NaN,NaN,NaN
1,ham,ok lar joking wif u oni,NaN,NaN,NaN
2,spam,free entry in a wkly comp to win fa cup final...,NaN,NaN,NaN
3,ham,u dun say so early hor u c already then say,NaN,NaN,NaN
4,ham,nah i dont think he goes to usf he lives aroun...,NaN,NaN,NaN

## Tokenization

In [26]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

df['Message'] = df['Message'].apply(word_tokenize)
df.head()

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ArunShrestha\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"[go, until, jurong, point, crazy, available, o...",NaN,NaN,NaN
1,ham,"[ok, lar, joking, wif, u, oni]",NaN,NaN,NaN
2,spam,"[free, entry, in, a, wkly, comp, to, win, fa, ...",NaN,NaN,NaN
3,ham,"[u, dun, say, so, early, hor, u, c, already, t...",NaN,NaN,NaN
4,ham,"[nah, i, dont, think, he, goes, to, usf, he, l...",NaN,NaN,NaN

## stop word removal

In [32]:
from nltk.corpus import stopwords 
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
df['Message'] = df['Message'].apply(lambda x: [word for word in x if word not in stop_words])
df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ArunShrestha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"[go, jurong, point, crazy, available, bugis, n...",NaN,NaN,NaN
1,ham,"[ok, lar, joking, wif, u, oni]",NaN,NaN,NaN
2,spam,"[free, entry, wkly, comp, win, fa, cup, final,...",NaN,NaN,NaN
3,ham,"[u, dun, say, early, hor, u, c, already, say]",NaN,NaN,NaN
4,ham,"[nah, dont, think, goes, usf, lives, around, t...",NaN,NaN,NaN

## stemming/lemmatization

In [33]:
from nltk.stem import PorterStemmer
import pandas as pd

stemmer = PorterStemmer()

def stem_words(words):
    return [stemmer.stem(word) for word in words]

df['stemmed_messages'] = df['Message'].apply(stem_words)
df.head()

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4,stemmed_messages
0,ham,"[go, jurong, point, crazy, available, bugis, n...",NaN,NaN,NaN,"[go, jurong, point, crazi, avail, bugi, n, gre..."
1,ham,"[ok, lar, joking, wif, u, oni]",NaN,NaN,NaN,"[ok, lar, joke, wif, u, oni]"
2,spam,"[free, entry, wkly, comp, win, fa, cup, final,...",NaN,NaN,NaN,"[free, entri, wkli, comp, win, fa, cup, final,..."
3,ham,"[u, dun, say, early, hor, u, c, already, say]",NaN,NaN,NaN,"[u, dun, say, earli, hor, u, c, alreadi, say]"
4,ham,"[nah, dont, think, goes, usf, lives, around, t...",NaN,NaN,NaN,"[nah, dont, think, goe, usf, live, around, tho..."

In [36]:
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    def get_wordnet_pos(word):
        tag = nltk.pos_tag([word])[0][1][0].upper()
        tag_dict = {"J": wordnet.ADJ,
                    "N": wordnet.NOUN,
                    "V": wordnet.VERB,
                    "R": wordnet.ADV}
        

        return tag_dict.get(tag, wordnet.NOUN)
    
    lemmas = [lemmatizer.lemmatize(token, get_wordnet_pos(token)) for token in tokens]

    return lemmas

df['lemmatized_messages'] = df['Message'].apply(lemmatize_tokens)
df.head()

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\ArunShrestha\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ArunShrestha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4,stemmed_messages,lemmatized_messages
0,ham,"[go, jurong, point, crazy, available, bugis, n...",NaN,NaN,NaN,"[go, jurong, point, crazi, avail, bugi, n, gre...","[go, jurong, point, crazy, available, bugis, n..."
1,ham,"[ok, lar, joking, wif, u, oni]",NaN,NaN,NaN,"[ok, lar, joke, wif, u, oni]","[ok, lar, joking, wif, u, oni]"
2,spam,"[free, entry, wkly, comp, win, fa, cup, final,...",NaN,NaN,NaN,"[free, entri, wkli, comp, win, fa, cup, final,...","[free, entry, wkly, comp, win, fa, cup, final,..."
3,ham,"[u, dun, say, early, hor, u, c, already, say]",NaN,NaN,NaN,"[u, dun, say, earli, hor, u, c, alreadi, say]","[u, dun, say, early, hor, u, c, already, say]"
4,ham,"[nah, dont, think, goes, usf, lives, around, t...",NaN,NaN,NaN,"[nah, dont, think, goe, usf, live, around, tho...","[nah, dont, think, go, usf, life, around, though]"